name: Terraform PR Checks
on:
  pull_request:
    paths:
      - 'terraform/**'

env:
  PROJECT: symchk
  ENV_NAME: dev
  TF_VERSION: 1.1.3
  TF_LINT_VERSION: v0.34.1

jobs:
  test-infra:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    timeout-minutes: 10
    concurrency: ci-${github.ref}-dev
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: ${{ env.TF_LINT_VERSION }}

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - name: Terraform Plan
        run: make plan > plan.txt

      - name: 'Terraform Plan'
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: `${const data = fs.readFileSync('./plan.txt', {encoding:'utf8', flag:'r'});}` });
