name: Web PR Checks
on:
  pull_request:
    paths:
      - 'apps/web/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn workspace @symchk/web install

      - name: Run formatting check
        run: yarn format:check

      - name: Lint web package
        run: yarn workspace @symchk/web lint

      - name: Build web package
        run: yarn workspace @symchk/web build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn workspace @symchk/web build
          start: yarn workspace @symchk/web start
          working-directory: ./apps/web
